version: "3"
services:

#    mysql:
#      image: mysql:5.7
#      container_name: middle-mysql
#      working_dir: /application
#      volumes:
#        - .:/application
#      environment:
#        - MYSQL_ROOT_PASSWORD=root
#        - MYSQL_DATABASE=middle
#        - MYSQL_USER=admin
#        - MYSQL_PASSWORD=admin

    webserver:
      image: nginx:alpine
      container_name: middle-webserver
      working_dir: /application
      extra_hosts:
        - "docker.backend:192.168.100.107"
      volumes:
        - .:/application
        - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8888:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: middle-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini
